=== Traviatti/LMSG04/preguntas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT preguntas (pregunta)+>
<!ELEMENT pregunta (tipo,text,opcion*,respuesta)>
<!ATTLIST pregunta id ID #REQUIRED>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT opcion (#PCDATA)>
<!ELEMENT respuesta (#PCDATA)>

=== Traviatti/LMSG04/preguntas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE preguntas SYSTEM "preguntas.dtd">
<preguntas>
<pregunta id='pregunta001'>
<tipo>text</tipo>
<text>Ciudad capital de España</text>
<respuesta>Madrid</respuesta>
</pregunta>
<pregunta id='pregunta002'>
<tipo>text</tipo>
<text>¿En qué año llegó el hombre a la luna?</text>
<respuesta>1969</respuesta>
</pregunta>
<pregunta id='pregunta003'>
<tipo>radio</tipo>
<text>¿Qué sistema numérico es el principial usado en la informática?</text>
<opcion>Octal</opcion>
<opcion>Binario</opcion> 
<opcion>Hexadecimal</opcion>
<respuesta>2</respuesta> <!-- 0, 1, 2 -->
</pregunta>
<pregunta id='pregunta004'>
<tipo>select</tipo>
<text>¿Cuál es el fruto del nogal?</text>
<opcion>Nuez</opcion>
<opcion>Manzana</opcion> 
<opcion>Piña</opcion>
<respuesta>1</respuesta> <!-- 0, 1, 2 -->
</pregunta>
<pregunta id='pregunta005'>
<tipo>select multiple</tipo>
<text>¿Cuál de estos tipos son navegadores web?</text>
<opcion>Chrome</opcion>
<opcion>Explorador</opcion> 
<opcion>Mozilla</opcion>
<opcion>Edger</opcion> 
<respuesta>1, 3</respuesta> <!-- 0, 1, 2, 3 -->
</pregunta>
<pregunta id='pregunta006'>
<tipo>radio</tipo>
<text>2 + 4 * 5 = ?</text>
<opcion>30</opcion>
<opcion>11</opcion> 
<opcion>22</opcion>
<respuesta>3</respuesta> <!-- 0, 1, 2 -->
</pregunta>
<pregunta id='pregunta007'>
<tipo>checkboxx</tipo>
<text>¿Cúal de éstos nombres pertenecen a una red social=</text>
<opcion>Facebool</opcion>
<opcion>Twider</opcion> 
<opcion>Facebook</opcion>
<respuesta>2</respuesta> <!-- 0, 1, 2 -->
</pregunta>
<pregunta id='pregunta008'>
<tipo>text</tipo>
<text>Cielo es a azul como noche es a...</text>
<respuesta>negro</respuesta>
</pregunta>
<pregunta id='pregunta009'>
<tipo>select</tipo>
<text>¿Puede el hombre volar por sí mismo?</text>
<opcion>Sí</opcion>
<opcion>No</opcion> 
<opcion>Llenguatge extrem multiplataforma</opcion>
<respuesta>1</respuesta> <!-- 0, 1 -->
</pregunta>
<pregunta id='pregunta010'>
<tipo>checkbox</tipo>
<text>¿Dónde puedes almacenar datos informáticos?</text>
<opcion>Disco Duro</opcion>
<opcion>Archivador</opcion> 
<opcion>USB</opcion>
<opcion>Cartapacio</opcion>
<respuesta>1, 3</respuesta> <!-- 0, 1, 2, 3 -->
</pregunta>
</preguntas>
